export const LOGIN = 'LOGIN';
export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const ALL_PRODUCTS_ERROR = 'ALL_PRODUCTS_ERROR';
export const ALL_PRODUCTS_WAIT = 'ALL_PRODUCTS_WAIT';
export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';
